// SPDX-FileCopyrightText: 2026 Jonas Sattler
// SPDX-License-Identifier: GPL-3.0-only

// Turn the two files the spikes write into one page a person can read.
//
// verify.tsv is a verdict per renderer per check and results.tsv is a row per
// cell; neither is worth reading as a file. gallery.md puts the verdicts beside
// the images they were reached on, which is the only form in which a "fail" is
// an argument rather than an assertion -- the Qt Graphs gap row means nothing
// until you have seen the straight line it draws across ten thousand samples
// that were never measured.
//
// Deliberately a program and not a script. It runs on Windows, it is built and
// therefore compiled, and the numbers in docs/PLOTTING-EVALUATION.md can be
// regenerated from a run rather than transcribed from one.

#include <QtCore/QCoreApplication>
#include <QtCore/QDir>
#include <QtCore/QFile>
#include <QtCore/QFileInfo>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QTextStream>

#include <cstdio>

namespace {

struct Table {
    QStringList columns;
    QList<QStringList> rows;
};

/// Read a tab-separated file whose first line is its header. Returns an empty
/// table when the file is missing, which the caller reports as a section it
/// could not write rather than as an empty section.
Table readTsv(const QString& path)
{
    Table table;
    QFile file(path);
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
        return table;
    }
    QTextStream stream(&file);
    bool first = true;
    while (!stream.atEnd()) {
        const QString line = stream.readLine();
        if (line.isEmpty()) {
            continue;
        }
        const QStringList fields = line.split(QLatin1Char('\t'));
        if (first) {
            table.columns = fields;
            first = false;
        } else {
            table.rows.append(fields);
        }
    }
    return table;
}

int columnOf(const Table& table, const char* name)
{
    return table.columns.indexOf(QLatin1String(name));
}

QString at(const QStringList& row, int column)
{
    return (column >= 0 && column < row.size()) ? row.at(column) : QString();
}

/// The order the renderers are reported in: whichever order they first appear
/// in the file, so re-running one of them does not reshuffle the page.
QStringList renderersIn(const Table& table, int column)
{
    QStringList order;
    for (const QStringList& row : table.rows) {
        const QString name = at(row, column);
        if (!name.isEmpty() && !order.contains(name)) {
            order.append(name);
        }
    }
    return order;
}

} // namespace

int main(int argc, char** argv)
{
    QCoreApplication application(argc, argv);

    QString directory = QStringLiteral(".");
    const QStringList arguments = QCoreApplication::arguments();
    for (int i = 1; i < arguments.size(); ++i) {
        if (arguments.at(i) == QLatin1String("--out") && i + 1 < arguments.size()) {
            directory = arguments.at(++i);
        } else {
            std::fprintf(stderr, "usage: %s --out DIR\n", argv[0]);
            return 2;
        }
    }

    const Table verify = readTsv(directory + QStringLiteral("/verify.tsv"));
    const Table bench = readTsv(directory + QStringLiteral("/results.tsv"));
    if (verify.rows.isEmpty() && bench.rows.isEmpty()) {
        std::fprintf(stderr,
                     "nothing to gather in %s. Run the spikes with --verify "
                     "and --bench first.\n",
                     qPrintable(directory));
        return 1;
    }

    QFile page(directory + QStringLiteral("/gallery.md"));
    if (!page.open(QIODevice::WriteOnly | QIODevice::Text)) {
        std::fprintf(stderr, "could not write %s\n", qPrintable(page.fileName()));
        return 1;
    }
    QTextStream out(&page);

    out << "<!--\n"
           "SPDX-FileCopyrightText: 2026 Jonas Sattler\n"
           "SPDX-License-Identifier: GPL-3.0-only\n"
           "-->\n\n"
           "# The evidence\n\n"
           "Generated by `plot-gallery`; every number and every image here came "
           "out of a run rather than out of a transcription. The argument they "
           "support is in `docs/PLOTTING-EVALUATION.md`.\n\n";

    // --- the correctness checks -------------------------------------------
    if (!verify.rows.isEmpty()) {
        const int renderer = columnOf(verify, "renderer");
        const int check = columnOf(verify, "check");
        const int verdict = columnOf(verify, "verdict");
        const int measure = columnOf(verify, "measure");
        const int detail = columnOf(verify, "detail");
        const int image = columnOf(verify, "image");

        const QStringList renderers = renderersIn(verify, renderer);

        QStringList checks;
        for (const QStringList& row : verify.rows) {
            const QString name = at(row, check);
            if (!name.isEmpty() && !checks.contains(name)) {
                checks.append(name);
            }
        }

        out << "## Is the picture true?\n\n";
        out << "| check |";
        for (const QString& name : renderers) {
            out << ' ' << name << " |";
        }
        out << "\n|---|";
        for (int i = 0; i < renderers.size(); ++i) {
            out << "---|";
        }
        out << '\n';

        for (const QString& name : checks) {
            out << "| " << name << " |";
            for (const QString& who : renderers) {
                QString cell = QStringLiteral("-");
                for (const QStringList& row : verify.rows) {
                    if (at(row, renderer) == who && at(row, check) == name) {
                        cell = at(row, verdict) + QStringLiteral(" (")
                               + at(row, measure) + QStringLiteral(")");
                        break;
                    }
                }
                out << ' ' << cell << " |";
            }
            out << '\n';
        }
        out << '\n';

        // What each check was measuring, once rather than once per renderer.
        out << "| check | what the number is |\n|---|---|\n";
        for (const QString& name : checks) {
            for (const QStringList& row : verify.rows) {
                if (at(row, check) == name) {
                    out << "| " << name << " | " << at(row, detail) << " |\n";
                    break;
                }
            }
        }
        out << '\n';

        for (const QString& name : checks) {
            out << "### " << name << "\n\n";
            for (const QString& who : renderers) {
                for (const QStringList& row : verify.rows) {
                    if (at(row, renderer) != who || at(row, check) != name) {
                        continue;
                    }
                    const QString file = at(row, image);
                    if (!file.isEmpty()) {
                        out << "**" << who << "** — " << at(row, verdict) << "\n\n"
                            << "![" << who << ' ' << name << "](" << file << ")\n\n";
                    }
                    break;
                }
            }
        }
    }

    // --- the grid ----------------------------------------------------------
    if (!bench.rows.isEmpty()) {
        const int renderer = columnOf(bench, "renderer");
        const int series = columnOf(bench, "series");
        const int points = columnOf(bench, "points");
        const int real = columnOf(bench, "real");
        const int skipped = columnOf(bench, "skipped");
        const QStringList renderers = renderersIn(bench, renderer);

        struct Column {
            const char* field;
            const char* title;
        };
        const Column reported[] = {
            {"cpu_p50", "Frame, median milliseconds"},
            {"cpu_p95", "Frame, 95th percentile milliseconds"},
            {"build_ms", "Handing over the data, milliseconds"},
            {"rss_mib", "Peak resident, MiB"},
            {"allocs", "Allocations over the whole gesture"},
        };

        for (const Column& column : reported) {
            const int field = columnOf(bench, column.field);
            if (field < 0) {
                continue;
            }
            out << "## " << column.title << "\n\n| series x points |";
            for (const QString& who : renderers) {
                out << ' ' << who << " |";
            }
            out << "\n|---|";
            for (int i = 0; i < renderers.size(); ++i) {
                out << "---|";
            }
            out << '\n';

            QStringList seen;
            for (const QStringList& row : bench.rows) {
                const QString key = at(row, series) + QStringLiteral(" x ")
                                    + at(row, points);
                if (seen.contains(key)) {
                    continue;
                }
                seen.append(key);
                out << "| " << key
                    << (at(row, real) == QLatin1String("1")
                            ? QStringLiteral(" **<- the real one**")
                            : QString())
                    << " |";
                for (const QString& who : renderers) {
                    QString cell = QStringLiteral("-");
                    for (const QStringList& other : bench.rows) {
                        if (at(other, renderer) != who
                            || at(other, series) != at(row, series)
                            || at(other, points) != at(row, points)) {
                            continue;
                        }
                        cell = at(other, skipped) == QLatin1String("1")
                                   ? QStringLiteral("_skipped_")
                                   : at(other, field);
                        break;
                    }
                    out << ' ' << cell << " |";
                }
                out << '\n';
            }
            out << '\n';
        }
    }

    std::printf("wrote %s\n", qPrintable(page.fileName()));
    return 0;
}
