#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Jonas Sattler
# SPDX-License-Identifier: GPL-3.0-only

# Render packaging/h5scope.svg into the raster icons the two platforms want.
#
# packaging/h5scope.svg is the source; the rasters beside it are generated by
# this script and committed, because neither a build nor a release should need
# a working SVG rasteriser to produce an icon. Run it after editing the SVG,
# and commit what changes.
#
#   h5scope.png       256x256, for the AppImage and the hicolor theme
#   h5scope.ico       16/24/32/48/64/128/256, for the Windows executable's
#                     resource -- see packaging/h5scope.rc.in
#   icons/h5scope-N   the same sizes below 256 as separate files, compiled into
#                     the binary as :/icons and handed to QGuiApplication as
#                     the window icon -- see src/gui/EmbeddedIcon.cpp. The 256
#                     is not repeated there: h5scope.png above is that render,
#                     and src/gui/CMakeLists.txt aliases it into the set.
#
# So one `rsvg-convert` per size feeds all three consumers, and the icon in the
# Windows resource, the icon in the AppImage and the icon the running window
# carries are the same bytes rather than three renders that agree by habit.
#
# Every size is rendered from the vector rather than resampled from the 256,
# which is what the small ones need: a 16x16 produced by downscaling a 256x256
# turns this icon's 3px grid lines into grey haze, where rendering at 16 draws
# only what the rasteriser can actually resolve there. The check at the end is
# what keeps that true rather than merely intended.
#
# The ICO is assembled by Pillow rather than by ImageMagick, which is the one
# surprising choice here. ImageMagick writes every entry as an uncompressed
# BMP, so the same seven images come to 372 KB instead of 21 KB -- and the
# 256x256 entry, which is the one that matters most and compresses best, is
# most of the difference.
#
# Needs: rsvg-convert (librsvg), python3 with Pillow.
# Usage: tools/make-icons.sh

set -euo pipefail

readonly repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
readonly svg="$repo_root/packaging/h5scope.svg"
readonly sizes=(16 24 32 48 64 128 256)

command -v rsvg-convert >/dev/null || {
  echo "error: rsvg-convert is not installed (librsvg)" >&2
  exit 1
}
python3 -c "import PIL" 2>/dev/null || {
  echo "error: python3 cannot import PIL (pip install Pillow)" >&2
  exit 1
}

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

for size in "${sizes[@]}"; do
  rsvg-convert --width="$size" --height="$size" \
               --output="$tmp/$size.png" "$svg"
done

cp "$tmp/256.png" "$repo_root/packaging/h5scope.png"

# Every size but the 256, which packaging/h5scope.png already is.
mkdir -p "$repo_root/packaging/icons"
for size in "${sizes[@]}"; do
  if [[ "$size" != 256 ]]; then
    cp "$tmp/$size.png" "$repo_root/packaging/icons/h5scope-$size.png"
  fi
done

SIZES="${sizes[*]}" TMP="$tmp" OUT="$repo_root/packaging/h5scope.ico" \
python3 - <<'PY'
import os
from PIL import Image, ImageChops

sizes = [int(s) for s in os.environ["SIZES"].split()]
tmp = os.environ["TMP"]
out = os.environ["OUT"]

rendered = {s: Image.open(f"{tmp}/{s}.png").convert("RGBA") for s in sizes}

# Saved from the largest with the rest appended: Pillow matches each requested
# size against the images it was given and only falls back to resampling the
# base when none of them is that size. Saving from the smallest instead
# silently drops every size above it, which is a one-entry .ico that still
# looks like a success.
largest = max(sizes)
rendered[largest].save(
    out, format="ICO",
    sizes=[(s, s) for s in sizes],
    append_images=[rendered[s] for s in sizes if s != largest])

# What the fallback above would have produced, rejected. If Pillow ever stops
# matching by size, every entry below 256 becomes a downscale of the 256 and
# the file is still a valid seven-entry icon -- so the failure is invisible
# unless it is looked for.
written = Image.open(out)
for s in sizes:
    entry = Image.open(out)
    entry.size = (s, s)
    entry = entry.convert("RGBA")
    if ImageChops.difference(entry, rendered[s]).getbbox() is not None:
        raise SystemExit(
            f"error: the {s}x{s} entry is not the {s}x{s} render. Pillow "
            f"resampled it from the {largest} instead of taking the image "
            f"it was given.")

print(f"{out}: {len(written.info['sizes'])} entries, "
      f"{os.path.getsize(out)} bytes")
PY

echo "wrote packaging/h5scope.png, packaging/h5scope.ico" \
     "and packaging/icons/ (${#sizes[@]} renders)"
